ARG url=localhost:30500/pytrtllm:put-your-version
FROM $url AS pytrtllm-builder

RUN pip install git+https://github.com/Dao-AILab/fast-hadamard-transform.git

COPY python.patch /app/tensorrt_llm/python.patch
RUN patch -p1 -i/app/tensorrt_llm/python.patch -d/usr/local/lib/python3.12/dist-packages
ENTRYPOINT ["/bin/bash", "-c", "exec \"$@\"", "--", "/usr/local/bin/trtllm-serve"]
