ARG url=localhost:30500/pytrtllm:put-your-version
FROM $url AS pytrtllm-builder

COPY python.patch /app/tensorrt_llm/python.patch
RUN patch -p1 -i/app/tensorrt_llm/python.patch -d/usr/local/lib/python3.12/dist-packages

RUN pip install --upgrade transformers
ENTRYPOINT ["/bin/bash", "-c", "exec \"$@\"", "--", "/usr/local/bin/trtllm-serve"]
