enable_attention_dp: false
pytorch_backend_config:
  enable_overlap_scheduler: true
  use_cuda_graph: true
  cuda_graph_max_batch_size: 8
  autotuner_enabled: false

speculative_config:
    decoding_type: Eagle
    max_draft_len: 3
    pytorch_eagle_weights_path: /data/tgi-data/fast_b200_vmaverick-eagle3-2x-ffn-hidden-size/fast_b200_vmaverick-eagle3-2x-ffn-hidden-size

kv_cache_config:
    # TODO: remove this once eagle3 and block reuse are compatible
    free_gpu_memory_fraction: 0.75
    enable_block_reuse: false
